#!/usr/bin/env bash
# requires: gcc
# 612_build_program_file_input_fast_path.sh — editing a file a build program
# declared with `rerun_if_changed` rebuilds, even on the fast path
# (mcpp 2026.9.5.4+).
#
# The fast path skips prepare_build when no SOURCE is newer than build.ninja,
# and prepare_build is where the build.mcpp cache is consulted. A data file is
# not a source: it has no C++ extension and does not live under src/, so the
# mtime sweep cannot see it, and the staleness check the fast path did run
# asked only about glob path SETS. Editing the file therefore left the header
# generated by the previous run in place, `mcpp build` reported
# "Finished dev in 0.00s", and the program kept compiling the previous bytes.
#
# The criterion is the program's OUTPUT, not a line of build log: a stale
# header and a fresh one differ in what the binary prints.
set -e

TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT
cd "$TMP"

"$MCPP" new probe > /dev/null; cd probe
rm -f src/*.cppm
mkdir -p data
printf 'first\n' > data/value.txt

cat > mcpp.toml <<'EOT'
[package]
name = "probe"
version = "0.1.0"
[language]
standard = "c++23"
modules = true
import_std = true

[targets.probe]
kind = "bin"
main = "src/main.cpp"
EOT

# A build program that reads a data file and writes a header from it. No
# action is submitted: the work happens while the program runs, which is the
# shape `mcpp.tools.embed` has and the shape the fast path used to skip.
cat > build.mcpp <<'EOT'
import std;
import mcpp;
int main() {
    const std::filesystem::path root(mcpp::manifest_dir());
    const std::filesystem::path gen(std::string(mcpp::out_dir()) + "/include");
    std::error_code ec;
    std::filesystem::create_directories(gen, ec);
    std::ifstream in(root / "data" / "value.txt");
    std::string value;
    std::getline(in, value);
    std::ofstream out(gen / "value.h", std::ios::trunc);
    out << "#pragma once\n#define PROBE_VALUE \"" << value << "\"\n";
    mcpp::rerun_if_changed((root / "data" / "value.txt").string().c_str());
    mcpp::include_dir(gen.string().c_str());
    return 0;
}
EOT

cat > src/main.cpp <<'EOT'
#include <cstdio>
#include "value.h"
int main() { std::printf("VALUE=%s\n", PROBE_VALUE); }
EOT

value() { "$MCPP" run 2>&1 | grep '^VALUE=' | tail -1; }

"$MCPP" build > b1.log 2>&1 || { cat b1.log; echo "FAIL: the first build failed"; exit 1; }
[[ "$(value)" == "VALUE=first" ]] || { echo "FAIL: the first build did not embed the first value"; exit 1; }

# Content only. The path set is unchanged, so a glob fingerprint cannot see
# this, and no source's mtime moves.
printf 'second\n' > data/value.txt

"$MCPP" build > b2.log 2>&1 || { cat b2.log; echo "FAIL: the second build failed"; exit 1; }
out="$(value)"
[[ "$out" == "VALUE=second" ]] || {
    echo "FAIL: a declared file input changed and the build replayed the old header ($out)"
    cat b2.log
    exit 1
}
echo "PASS: a declared file input is compared on the fast path"

# The mirror half: an unchanged input must NOT force work. Two builds in a row
# with nothing touched, and the second one has to take the fast path -- without
# this the fix could be "always rebuild", which passes the assertion above and
# is not the behaviour asked for.
"$MCPP" build > b3.log 2>&1
grep -qE 'Finished .* in ' b3.log || { cat b3.log; echo "FAIL: the third build did not finish"; exit 1; }
"$MCPP" build > b4.log 2>&1
grep -q 'Compiling probe' b4.log && { cat b4.log; echo "FAIL: an unchanged input recompiled the project"; exit 1; }
echo "PASS: an unchanged input still takes the fast path"
