#!/usr/bin/env bash
# requires: elf
# 693 -- the root package's build program reads the link form each dependency
# takes in this build (#642 E2): `mcpp::dep_linkage(name)`, over
# MCPP_DEP_<NAME>_LINKAGE, answers "static" or "shared" from the same
# resolution that decides what is linked. A dependency's own program is not
# offered the forms.
#
# Legs:
#   A. A package whose default form is shared and a package whose only sources
#      are generated by its own build program, requested shared: the root
#      program reads `fw=shared gen=shared`, and both shared libraries exist.
#      The generated-only package is the case a computation placed before the
#      dependency programs would read as having no sources.
#   B. A second build with nothing changed does not re-run the root program.
#   C. The dependency's default changes to static in its own manifest, the root
#      manifest unchanged: the root program re-runs and reads `fw=static`, and
#      no `libfw.so` is built.
#   D. The consumer's edge asks for shared again: the program reads
#      `fw=shared`, matching `libfw.so`.
#   E. In every leg, a dependency's program reads "" for its own dependency
#      while dep_dir() answers for the same name; `gen`'s program fails the
#      build otherwise.
#   F. A dependency whose manifest states `namespace = "ns"` and `name =
#      "nsfw"` is named `ns.nsfw` by its consumer, and the root program reads
#      both `dep_linkage` and `dep_dir` under that spelling as well as under the
#      bare name.
set -e

TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

fail() { echo "FAIL: $1"; shift; for f in "$@"; do echo "--- $f ---"; cat "$f" 2>/dev/null; done; exit 1; }

# A leaf library, depended on by `gen`.
mkdir -p "$TMP/leaf/src"
printf '[package]\nname = "leaf"\nversion = "0.1.0"\n[targets.leaf]\nkind = "lib"\n' > "$TMP/leaf/mcpp.toml"
printf 'int leaf_value() { return 1; }\n' > "$TMP/leaf/src/leaf.cpp"

# `fw`: a library whose default form is shared.
mkdir -p "$TMP/fw/src"
write_fw() {  # write_fw <default form>
    printf '[package]\nname = "fw"\nversion = "0.1.0"\n[targets.fw]\nkind = "lib"\nlinkage = "%s"\n' \
        "$1" > "$TMP/fw/mcpp.toml"
}
write_fw shared
printf 'int fw_value() { return 40; }\n' > "$TMP/fw/src/fw.cpp"

# `gen`: no source of its own on disk; its build program generates the one
# translation unit it has, and asserts what a dependency's program is offered.
mkdir -p "$TMP/gen"
cat > "$TMP/gen/mcpp.toml" <<'EOF'
[package]
name    = "gen"
version = "0.1.0"
[modules]
sources = []
[dependencies]
leaf = { path = "../leaf" }
[targets.gen]
kind = "lib"
EOF
cat > "$TMP/gen/build.mcpp" <<'EOF'
#include <cstdio>
#include <string>
import mcpp;
int main() {
    const char* dir  = mcpp::dep_dir("leaf");
    const char* form = mcpp::dep_linkage("leaf");
    if (dir == nullptr || dir[0] == '\0') {
        std::fprintf(stderr, "gen: dep_dir(leaf) is empty\n");
        return 1;
    }
    if (form != nullptr && form[0] != '\0') {
        std::fprintf(stderr, "gen: a dependency's program was offered dep_linkage(leaf)=%s\n", form);
        return 1;
    }
    std::string out = std::string(mcpp::out_dir()) + "/gen.cpp";
    std::FILE* f = std::fopen(out.c_str(), "w");
    std::fprintf(f, "int leaf_value();\nint gen_value() { return leaf_value() + 1; }\n");
    std::fclose(f);
    mcpp::generated("gen.cpp");
    return 0;
}
EOF

# The root: its build program records what it reads, one line per run.
mkdir -p "$TMP/app/src"
write_app() {  # write_app <fw edge options>
    printf '[package]\nname = "app"\nversion = "0.1.0"\n[dependencies]\nfw = { path = "../fw"%s }\ngen = { path = "../gen", linkage = "shared" }\n' \
        "$1" > "$TMP/app/mcpp.toml"
}
write_app ''
cat > "$TMP/app/build.mcpp" <<'EOF'
#include <cstdio>
#include <string>
import mcpp;
int main() {
    std::string line = std::string("fw=") + mcpp::dep_linkage("fw")
                     + " gen=" + mcpp::dep_linkage("gen") + "\n";
    std::string log = std::string(mcpp::manifest_dir()) + "/runs.log";
    std::FILE* f = std::fopen(log.c_str(), "a");
    std::fputs(line.c_str(), f);
    std::fclose(f);
    return 0;
}
EOF
printf 'int fw_value();\nint gen_value();\nint main() { return fw_value() + gen_value() == 42 ? 0 : 1; }\n' \
    > "$TMP/app/src/main.cpp"

cd "$TMP/app"
libfw()  { find target -name libfw.so  | head -1; }
libgen() { find target -name libgen.so | head -1; }

# ── A ──────────────────────────────────────────────────────────────────────
"$MCPP" build > a.log 2>&1 || fail "A: build failed" a.log
[ "$(tail -1 runs.log)" = "fw=shared gen=shared" ] || fail "A: the root program read '$(tail -1 runs.log)'" a.log
[ -n "$(libfw)" ]  || fail "A: no libfw.so" a.log
[ -n "$(libgen)" ] || fail "A: no libgen.so for a package whose sources are all generated" a.log
"$(find target -type f -name app -path '*/bin/*' | head -1)" || fail "A: the program did not run"

# ── B ──────────────────────────────────────────────────────────────────────
"$MCPP" build > b.log 2>&1 || fail "B: build failed" b.log
[ "$(wc -l < runs.log)" -eq 1 ] || fail "B: an unchanged build re-ran the root program" runs.log

# ── C ──────────────────────────────────────────────────────────────────────
write_fw static
"$MCPP" build > c.log 2>&1 || fail "C: build failed" c.log
[ "$(wc -l < runs.log)" -eq 2 ] || fail "C: a changed dependency form did not re-run the root program" runs.log c.log
[ "$(tail -1 runs.log)" = "fw=static gen=shared" ] || fail "C: the root program read '$(tail -1 runs.log)'" c.log
rm -rf target
"$MCPP" build > c2.log 2>&1 || fail "C: clean build failed" c2.log
[ -z "$(libfw)" ] || fail "C: libfw.so was built while the program read static" c2.log

# ── D ──────────────────────────────────────────────────────────────────────
write_app ', linkage = "shared"'
"$MCPP" build > d.log 2>&1 || fail "D: build failed" d.log
[ "$(tail -1 runs.log)" = "fw=shared gen=shared" ] || fail "D: the root program read '$(tail -1 runs.log)'" d.log
[ -n "$(libfw)" ] || fail "D: no libfw.so while the program read shared" d.log

# ── F ──────────────────────────────────────────────────────────────────────
mkdir -p "$TMP/nsfw/src" "$TMP/nsapp/src"
printf '[package]\nnamespace = "ns"\nname = "nsfw"\nversion = "0.1.0"\n[targets.nsfw]\nkind = "lib"\nlinkage = "shared"\n' \
    > "$TMP/nsfw/mcpp.toml"
printf 'int nsfw_value() { return 42; }\n' > "$TMP/nsfw/src/nsfw.cpp"
printf '[package]\nname = "nsapp"\nversion = "0.1.0"\n[dependencies]\nns.nsfw = { path = "../nsfw" }\n' \
    > "$TMP/nsapp/mcpp.toml"
printf 'int nsfw_value();\nint main() { return nsfw_value() == 42 ? 0 : 1; }\n' > "$TMP/nsapp/src/main.cpp"
cat > "$TMP/nsapp/build.mcpp" <<'EOF'
#include <cstdio>
#include <string>
import mcpp;
int main() {
    std::string line = std::string("qualified=") + mcpp::dep_linkage("ns.nsfw")
                     + " bare=" + mcpp::dep_linkage("nsfw")
                     + " dir=" + (mcpp::dep_dir("ns.nsfw")[0] != '\0' ? "yes" : "no") + "\n";
    std::string log = std::string(mcpp::manifest_dir()) + "/runs.log";
    std::FILE* f = std::fopen(log.c_str(), "a");
    std::fputs(line.c_str(), f);
    std::fclose(f);
    return 0;
}
EOF
cd "$TMP/nsapp"
"$MCPP" build > f.log 2>&1 || fail "F: build failed" f.log
[ "$(tail -1 runs.log)" = "qualified=shared bare=shared dir=yes" ] \
    || fail "F: the root program read '$(tail -1 runs.log)'" f.log

echo "OK"
