#!/usr/bin/env bash
# requires: gcc python3 fresh-sandbox
# 844 -- a planned build of a workspace root keeps ONE mcpp.lock entry per
# identity, spelled as the root's manifest spells it (defect F11).
#
# A workspace root that also has a [package] and declares an index dependency
# under `[dependencies.mcpplibs]` has the map key `mcpplibs.cmdline`, and
# 2026.9.28.3 locked it under that name. Since 2026.9.29.1 a build of the root
# is a plan of a workspace under a virtual root whose own dependency table is
# empty, so the lock name fell through to the qualified name `cmdline` (with a
# hash taken over that spelling), and the partial-workspace merge, which keyed
# prior entries by the spelled name, kept the old entry beside it: two entries
# for one identity, and a committed lock modified by every build.
#
# (a) a lock in the 2026.9.28.3 spelling is left byte-identical;
# (b) a lock that holds both spellings is reduced to one entry;
# (c) a second planned build leaves the result byte-identical.
#
# The dependency is served by a project-local index and pre-extracted into the
# private xlings data directory, so the build touches no network.
set -e

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
fail() { echo "FAIL: $1"; [ -n "${2:-}" ] && cat "$2"; exit 1; }

export MCPP_HOME="$TMP/mcpp-home"
source "$(dirname "$0")/_inherit_toolchain.sh"

mkdir -p "$TMP/ws" && cd "$TMP/ws"

mkdir -p local-index/pkgs/c
cat > local-index/pkgs/c/cmdline.lua <<'EOF'
package = {
    spec = "1",
    namespace = "mcpplibs",
    name = "cmdline",
    description = "fixture for the one-entry-per-identity lock (F11)",
    licenses = {"MIT"},
    type = "package",
    xpm = { linux = { ["1.0.0"] = {
        url = "https://example.invalid/cmdline-1.0.0.tar.gz",
        sha256 = "0000000000000000000000000000000000000000000000000000000000000000",
    } } },
    mcpp = {
        language = "c++23",
        import_std = false,
        sources = { "src/cmdline.cppm" },
        targets = { ["cmdline"] = { kind = "lib" } },
        deps = {},
    },
}
EOF
XP=".mcpp/.xlings/data/xpkgs/mcpplibs-x-cmdline/1.0.0"
mkdir -p "$XP/src"
cat > "$XP/src/cmdline.cppm" <<'EOF'
export module fixture.cmdline;
export int cmdline_value() { return 7; }
EOF
printf 'ok\n' > "$XP/.mcpp_ok"

mkdir -p src m/src
cat > mcpp.toml <<EOF
[package]
name    = "ws"
version = "0.1.0"

[workspace]
members = ["m"]

[indices]
default = { path = "local-index" }

[dependencies.mcpplibs]
cmdline = "1.0.0"

[targets.ws]
kind = "bin"
main = "src/main.cpp"
EOF
cat > src/main.cpp <<'EOF'
import fixture.cmdline;
int main() { return cmdline_value() == 7 ? 0 : 1; }
EOF
cat > m/mcpp.toml <<'EOF'
[package]
name    = "m"
version = "0.1.0"

[targets.m]
kind = "lib"

[build]
sources = ["src/m.cppm"]
EOF
cat > m/src/m.cppm <<'EOF'
export module m;
export int m_value() { return 1; }
EOF

# The hash 2026.9.28.3 recorded: FNV-1a over "<namespace>:<name>@<version>",
# name spelled as the root's map key.
digest() {
    python3 - "$1" <<'EOF'
import sys
h = 0xcbf29ce484222325
for b in sys.argv[1].encode():
    h ^= b
    h = (h * 0x100000001b3) & 0xffffffffffffffff
print("fnv1a:%016x" % h)
EOF
}
OLD_HASH=$(digest "mcpplibs:mcpplibs.cmdline@1.0.0")
NEW_HASH=$(digest "mcpplibs:cmdline@1.0.0")

write_old_lock() {
    cat > mcpp.lock <<EOF
# Auto-generated by mcpp. Do not edit by hand.
# Records what this build resolved. It does not yet pin future builds:
# index dependencies are re-resolved from their constraints each time.
# dev-dependencies are excluded: only \`mcpp test\` resolves them, and this
# file must not change depending on which command ran last.
version = 2

[package."mcpplibs.cmdline"]
namespace = "mcpplibs"
version = "1.0.0"
source  = "index+mcpplibs@1.0.0"
hash    = "$OLD_HASH"

EOF
}
entries() { grep -c '^\[package\.' mcpp.lock || true; }

# (a) the committed lock survives a planned build of the root member.
write_old_lock
cp mcpp.lock lock.before
"$MCPP" build > build.log 2>&1 || fail "the planned build did not succeed" build.log
cmp -s lock.before mcpp.lock || {
    diff lock.before mcpp.lock || true
    fail "(a) a planned build rewrote a lock in the 2026.9.28.3 spelling"
}

# (b) a lock holding both spellings is reduced to one entry per identity.
cat >> mcpp.lock <<EOF
[package."cmdline"]
namespace = "mcpplibs"
version = "1.0.0"
source  = "index+mcpplibs@1.0.0"
hash    = "$NEW_HASH"

EOF
[ "$(entries)" = 2 ] || fail "the fixture lock does not hold two entries" mcpp.lock
# A build whose inputs are unchanged replays the previous one without planning,
# and so without writing the lock; a source edit makes the next one a plan.
echo "// touched" >> src/main.cpp
"$MCPP" build > build2.log 2>&1 || fail "the second planned build did not succeed" build2.log
[ "$(entries)" = 1 ] || fail "(b) the lock still holds $(entries) entries for one identity" mcpp.lock
cmp -s lock.before mcpp.lock || {
    diff lock.before mcpp.lock || true
    fail "(b) the surviving entry is not the one 2026.9.28.3 wrote"
}

# (c) another planned build leaves it byte-identical.
echo "// touched again" >> src/main.cpp
"$MCPP" build > build3.log 2>&1 || fail "the third planned build did not succeed" build3.log
cmp -s lock.before mcpp.lock || fail "(c) a repeated planned build changed the lock" mcpp.lock

# --locked reads the same identities.
echo "// and again" >> src/main.cpp
MCPP_LOCKED=1 "$MCPP" build > build4.log 2>&1 || fail "--locked reported drift on an unchanged lock" build4.log

echo "PASS: 844_a_planned_build_keeps_one_lock_entry_per_identity"
