// bench.fixture.buildfiles — one project description per engine, for one variant.
//
// These files are what makes the comparison fair or meaningless, so each emitter
// pins the same four things: C++23, the same source set, the same optimisation
// level, and one executable. Anything an engine adds beyond that is noted in the
// emitted file itself, so a reader of the fixture can see the asymmetry without
// reading this module.
//
// `import std;` is deliberately ABSENT from every generated project. Engines
// differ wildly in how (and whether) they can build the std module — CMake needs
// a per-version experimental UUID, meson has no story at all — and that
// difference would dominate the measurement. The fixture reaches the standard
// library through the global module fragment instead, which every engine handles
// identically. The suite measures MODULE MACHINERY, not std-module support.
export module bench.fixture.buildfiles;

import std;
import bench.protocol;
import bench.fixture.generate;

export namespace bench::fixture {

// Collects the source lists a build description needs, derived from the variant
// rather than by globbing — a generator that guesses its own output is one
// rename away from silently building less than it claims.
struct SourceSet {
    std::vector<std::string> module_interfaces;   // .cppm
    std::vector<std::string> plain_sources;       // .cpp (incl. main + impl units)
};

inline SourceSet source_set(Variant variant, const Shape& s) {
    SourceSet set;
    for (int k = 0; k < s.units; ++k) {
        const auto name = std::format("unit_{}", k);
        if (variant == Variant::Headers) {
            set.plain_sources.push_back(std::format("src/{}.cpp", name));
        } else {
            set.module_interfaces.push_back(std::format("src/{}.cppm", name));
            if (variant == Variant::ModulesImpl)
                set.plain_sources.push_back(std::format("src/{}_impl.cpp", name));
        }
    }
    set.plain_sources.push_back("src/main.cpp");
    return set;
}

namespace detail {

inline void write(const std::filesystem::path& p, const std::string& text) {
    std::ofstream out(p, std::ios::binary | std::ios::trunc);
    out << text;
}

inline std::string join(const std::vector<std::string>& v, std::string_view sep,
                        std::string_view prefix = "", std::string_view suffix = "") {
    std::string out;
    for (std::size_t i = 0; i < v.size(); ++i) {
        if (i) out += sep;
        out += std::format("{}{}{}", prefix, v[i], suffix);
    }
    return out;
}

}  // namespace detail

// --- mcpp -----------------------------------------------------------------

inline void emit_mcpp(const std::filesystem::path& root, Variant variant, const Shape&) {
    // mcpp infers the source glob and the binary target from src/main.cpp, so
    // the manifest only has to state what cannot be inferred.
    std::string toml =
        "[package]\n"
        "name        = \"fx\"\n"
        "version     = \"0.1.0\"\n"
        "description = \"bench fixture\"\n"
        "\n"
        "[build]\n"
        "default-profile = \"release\"\n";
    toml += variant == Variant::Headers ? "include_dirs = [\"include\"]\n"
                                        : "include_dirs = [\"src\"]\n";
    // The toolchain is PINNED, matching every other mcpp project in this repo.
    // Relying on the machine's global default makes the fixture build depend on
    // ambient state — it works on a developer box that has one and fails on a
    // fresh CI sandbox that does not, which is exactly how this surfaced: green
    // locally, "seed build exited 1" on the runner.
    toml += "\n[toolchain]\n"
            "default = \"gcc@16.1.0\"\n"
            "macos   = \"llvm@22.1.8\"\n"
            "windows = \"llvm@20.1.7\"\n";
    detail::write(root / "mcpp.toml", toml);
}

// --- cmake ----------------------------------------------------------------

inline void emit_cmake(const std::filesystem::path& root, Variant variant, const Shape& s) {
    const auto set = source_set(variant, s);
    std::string cm =
        "# Generated by bench.fixture.buildfiles — do not edit.\n"
        "cmake_minimum_required(VERSION 3.28)\n"
        "project(fx CXX)\n"
        "set(CMAKE_CXX_STANDARD 23)\n"
        "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
        "set(CMAKE_CXX_EXTENSIONS OFF)\n"
        "\n";
    cm += std::format("add_executable(fx\n  {}\n)\n",
                      detail::join(set.plain_sources, "\n  "));
    if (!set.module_interfaces.empty()) {
        // FILE_SET CXX_MODULES is the only way CMake learns that these are
        // interface units; listing them as plain sources compiles them as
        // ordinary TUs and the link fails with missing module symbols.
        cm += std::format("target_sources(fx\n  PRIVATE\n    FILE_SET CXX_MODULES FILES\n      {}\n)\n",
                          detail::join(set.module_interfaces, "\n      "));
    }
    cm += std::format("target_include_directories(fx PRIVATE {})\n",
                      variant == Variant::Headers ? "include" : "src");
    detail::write(root / "CMakeLists.txt", cm);
}

// --- xmake ----------------------------------------------------------------

inline void emit_xmake(const std::filesystem::path& root, Variant variant, const Shape&) {
    std::string lua =
        "-- Generated by bench.fixture.buildfiles — do not edit.\n"
        "set_project(\"fx\")\n"
        "set_languages(\"c++23\")\n"
        "add_rules(\"mode.debug\", \"mode.release\")\n"
        "\n"
        "target(\"fx\")\n"
        "    set_kind(\"binary\")\n";
    if (variant == Variant::Headers) {
        lua += "    add_files(\"src/*.cpp\")\n"
               "    add_includedirs(\"include\")\n";
    } else {
        lua += "    add_files(\"src/*.cppm\")\n"
               "    add_files(\"src/*.cpp\")\n"
               "    add_includedirs(\"src\")\n"
               "    set_policy(\"build.c++.modules\", true)\n";
        // The fixture never says `import std;`, so xmake must not spend time
        // building the std module for it either — otherwise this engine pays a
        // cost none of the others do.
        lua += "    set_policy(\"build.c++.modules.std\", false)\n";
    }
    detail::write(root / "xmake.lua", lua);
}

// --- meson ----------------------------------------------------------------

inline void emit_meson(const std::filesystem::path& root, Variant variant, const Shape& s) {
    // Headers variant only — see bench.engines.meson for why. Emitting a module
    // project meson cannot build would turn an honest "unavailable" into a
    // confusing failure.
    if (variant != Variant::Headers) return;
    const auto set = source_set(variant, s);
    std::string mb =
        "# Generated by bench.fixture.buildfiles — do not edit.\n"
        "project('fx', 'cpp', default_options: ['cpp_std=c++23'])\n"
        "\n";
    mb += std::format("executable('fx',\n  [{}],\n  include_directories: include_directories('include'))\n",
                      detail::join(set.plain_sources, ", ", "'", "'"));
    detail::write(root / "meson.build", mb);
}

// --- bazel ----------------------------------------------------------------

inline void emit_bazel(const std::filesystem::path& root, Variant variant, const Shape& s) {
    if (variant != Variant::Headers) return;   // same reasoning as meson
    const auto set = source_set(variant, s);

    // bzlmod. `rules_cc` is NOT optional here: bazel 9 removed the built-in
    // cc_binary, so a BUILD file without the load() fails with "This rule has
    // been removed from Bazel". The dependency is fetched from the Bazel Central
    // Registry on first use and cached outside the workspace, so it is paid once
    // by the untimed seed build rather than by any measurement.
    detail::write(root / "MODULE.bazel",
                  "module(name = \"fx\", version = \"0.1.0\")\n"
                  "bazel_dep(name = \"rules_cc\", version = \"0.1.1\")\n");

    std::string bd =
        "# Generated by bench.fixture.buildfiles — do not edit.\n"
        "load(\"@rules_cc//cc:defs.bzl\", \"cc_binary\")\n"
        "\n"
        "cc_binary(\n"
        "    name = \"fx\",\n";
    // Headers are listed in srcs, not hdrs: cc_binary has no hdrs attribute, and
    // an undeclared header is a hard error under bazel's sandbox rather than the
    // silent include it would be elsewhere.
    std::vector<std::string> srcs = set.plain_sources;
    for (int k = 0; k < s.units; ++k) srcs.push_back(std::format("include/unit_{}.hpp", k));
    srcs.push_back("include/fixture_support.hpp");
    bd += std::format("    srcs = [{}],\n", detail::join(srcs, ", ", "\"", "\""));
    bd += "    includes = [\"include\"],\n";
    bd += "    copts = [\"-std=c++23\"],\n";
    bd += ")\n";
    detail::write(root / "BUILD.bazel", bd);
}

// Emits every build description a fixture instance can need. Engines that do
// not support the variant simply get no file, and their adapter reports
// `unavailable` with a reason rather than failing to find one.
inline void emit_all(const std::filesystem::path& root, Variant variant, const Shape& s) {
    emit_mcpp(root, variant, s);
    emit_cmake(root, variant, s);
    emit_xmake(root, variant, s);
    emit_meson(root, variant, s);
    emit_bazel(root, variant, s);
}

}  // namespace bench::fixture
