// bench.fixture.buildfiles — implementation.
//
// `module bench.fixture.buildfiles;` with no `export`: an implementation unit, so nothing below
// reaches an importer's BMI. Every engine's build description is emitted
// here; the interface is one function per engine plus `emit_all`.
module bench.fixture.buildfiles;

import std;
import bench.protocol;
import bench.toolchain;
import bench.fixture.generate;

namespace bench::fixture {

namespace detail {

void write(const std::filesystem::path& p, const std::string& text) {
    std::ofstream out(p, std::ios::binary | std::ios::trunc);
    out << text;
}

std::string join(const std::vector<std::string>& v, std::string_view sep,
                        std::string_view prefix, std::string_view suffix) {
    std::string out;
    for (std::size_t i = 0; i < v.size(); ++i) {
        if (i) out += sep;
        out += std::format("{}{}{}", prefix, v[i], suffix);
    }
    return out;
}

std::string trim_copy(std::string_view s) {
    while (!s.empty() && s.front() == ' ') s.remove_prefix(1);
    while (!s.empty() && s.back()  == ' ') s.remove_suffix(1);
    return std::string(s);
}

}  // namespace detail

SourceSet source_set(Variant variant, const Shape& s) {
    SourceSet set;
    for (int k = 0; k < s.units; ++k) {
        const auto name = std::format("unit_{}", k);
        if (variant == Variant::Headers) {
            set.plain_sources.push_back(std::format("src/{}.cpp", name));
        } else {
            set.module_interfaces.push_back(std::format("src/{}.cppm", name));
            if (variant == Variant::ModulesImpl)
                set.plain_sources.push_back(std::format("src/{}_impl.cpp", name));
        }
    }
    set.plain_sources.push_back("src/main.cpp");
    return set;
}

void emit_mcpp(const std::filesystem::path& root, Variant variant, const Shape&,
                      std::string_view compiler) {
    // mcpp infers the source glob and the binary target from src/main.cpp, so
    // the manifest only has to state what cannot be inferred.
    std::string toml =
        "[package]\n"
        "name        = \"fx\"\n"
        "version     = \"0.1.0\"\n"
        "description = \"bench fixture\"\n"
        "\n"
        "[build]\n"
        "default-profile = \"release\"\n";
    toml += variant == Variant::Headers ? "include_dirs = [\"include\"]\n"
                                        : "include_dirs = [\"src\"]\n";
    // The toolchain is PINNED, matching every other mcpp project in this repo.
    // Relying on the machine's global default makes the fixture build depend on
    // ambient state — it works on a developer box that has one and fails on a
    // fresh CI sandbox that does not, which is exactly how this surfaced: green
    // locally, "seed build exited 1" on the runner.
    //
    // It also FOLLOWS `--compiler`. mcpp resolves its own toolchain and ignores
    // the flag every other engine honours, so pinning gcc here while the harness
    // hands clang to cmake/xmake/bazel would turn the table into a compiler
    // comparison without saying so.
    //
    // The VERSION comes from bench.toolchain, which is also where the harness
    // looks the payload driver up. Spelling it here as well is how the two
    // drifted the first time: the manifest said gcc@16.1.0 and CI handed every
    // other engine the runner's gcc 13.
    toml += "\n[toolchain]\n";
    toml += std::format("default = \"{}\"\n", toolchain::mcpp_pin(compiler));
    detail::write(root / "mcpp.toml", toml);
}

void emit_cmake(const std::filesystem::path& root, Variant variant, const Shape& s,
                       std::string_view compiler) {
    const auto set = source_set(variant, s);
    // The payload flags go in BEFORE project(), because cmake's "can the
    // compiler build a trivial program" probe runs during project() — and a
    // bare registry gcc fails that probe at the LINK with `cannot find crt1.o`,
    // reported as a configure error that never mentions a sysroot.
    const auto pf = toolchain::payload_flags(compiler);
    std::string cm =
        "# Generated by bench.fixture.buildfiles — do not edit.\n"
        "cmake_minimum_required(VERSION 3.28)\n";
    if (!pf.compile.empty() || !pf.link.empty()) {
        cm += std::format("set(CMAKE_CXX_FLAGS \"${{CMAKE_CXX_FLAGS}}{}\")\n"
                          "set(CMAKE_C_FLAGS   \"${{CMAKE_C_FLAGS}}{}\")\n"
                          "set(CMAKE_EXE_LINKER_FLAGS \"${{CMAKE_EXE_LINKER_FLAGS}}{}\")\n",
                          pf.compile, pf.compile, pf.link);
    }
    cm += "project(fx CXX)\n"
        "set(CMAKE_CXX_STANDARD 23)\n"
        "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
        "set(CMAKE_CXX_EXTENSIONS OFF)\n"
        "\n";
    cm += std::format("add_executable(fx\n  {}\n)\n",
                      detail::join(set.plain_sources, "\n  "));
    if (!set.module_interfaces.empty()) {
        // FILE_SET CXX_MODULES is the only way CMake learns that these are
        // interface units; listing them as plain sources compiles them as
        // ordinary TUs and the link fails with missing module symbols.
        cm += std::format("target_sources(fx\n  PRIVATE\n    FILE_SET CXX_MODULES FILES\n      {}\n)\n",
                          detail::join(set.module_interfaces, "\n      "));
    }
    cm += std::format("target_include_directories(fx PRIVATE {})\n",
                      variant == Variant::Headers ? "include" : "src");
    detail::write(root / "CMakeLists.txt", cm);
}

void emit_xmake(const std::filesystem::path& root, Variant variant, const Shape&,
                       std::string_view compiler) {
    const auto pf = toolchain::payload_flags(compiler);
    std::string lua =
        "-- Generated by bench.fixture.buildfiles — do not edit.\n"
        "set_project(\"fx\")\n"
        "set_languages(\"c++23\")\n"
        "add_rules(\"mode.debug\", \"mode.release\")\n"
        "\n"
        "target(\"fx\")\n"
        "    set_kind(\"binary\")\n";
    if (variant == Variant::Headers) {
        lua += "    add_files(\"src/*.cpp\")\n"
               "    add_includedirs(\"include\")\n";
    } else {
        lua += "    add_files(\"src/*.cppm\")\n"
               "    add_files(\"src/*.cpp\")\n"
               "    add_includedirs(\"src\")\n"
               "    set_policy(\"build.c++.modules\", true)\n";
        // The fixture never says `import std;`, so xmake must not spend time
        // building the std module for it either — otherwise this engine pays a
        // cost none of the others do.
        lua += "    set_policy(\"build.c++.modules.std\", false)\n";
    }
    // PIE MUST BE EXPLICIT ON BOTH SIDES. The payload gcc defaults to a PIE
    // link on the CI runners and to a non-PIE link on some developer boxes, so
    // compiling without `-fPIE` produced objects the linker then refused:
    //     relocation R_X86_64_32 against `.rodata.str1.1' can not be used
    //     when making a PIE object; recompile with -fPIE
    //     ld: failed to set dynamic section sizes: bad value
    // Twelve fixture cells red on CI, green locally — the difference was the
    // driver's default, not the engine. mcpp and cmake produce PIE here (the
    // bazel adapter passes --force_pic for the same reason), so saying it out
    // loud keeps all four arms producing the same kind of executable.
    lua += "    add_cxflags(\"-fPIE\", {force = true})\n";
    lua += "    add_ldflags(\"-pie\", {force = true})\n";

    // Same payload flags as the cmake arm: xmake is handed the driver through
    // CXX, and a registry gcc without -B/--sysroot cannot link.
    if (!pf.compile.empty())
        lua += std::format("    add_cxflags(\"{}\", {{force = true}})\n",
                           detail::trim_copy(pf.compile));
    if (!pf.link.empty())
        lua += std::format("    add_ldflags(\"{}\", {{force = true}})\n",
                           detail::trim_copy(pf.link));
    detail::write(root / "xmake.lua", lua);
}

void emit_bazel(const std::filesystem::path& root, Variant variant, const Shape& s) {
    const auto set = source_set(variant, s);

    // bzlmod. `rules_cc` is NOT optional: bazel 9 removed the built-in cc_binary,
    // so a BUILD file without the load() fails with "This rule has been removed
    // from Bazel". The version matters too — `module_interfaces` only exists in
    // recent rules_cc (0.1.x does not have it, which is what made bazel look like
    // it could not build modules at all).
    detail::write(root / "MODULE.bazel",
                  "module(name = \"fx\", version = \"0.1.0\")\n"
                  "bazel_dep(name = \"rules_cc\", version = \"0.2.22\")\n");

    std::string bd =
        "# Generated by bench.fixture.buildfiles — do not edit.\n"
        "load(\"@rules_cc//cc:defs.bzl\", \"cc_binary\")\n"
        "\n"
        "cc_binary(\n"
        "    name = \"fx\",\n";

    // Headers are listed in srcs, not hdrs: cc_binary has no hdrs attribute, and
    // an undeclared header is a hard error under bazel's sandbox rather than the
    // silent include it would be elsewhere.
    std::vector<std::string> srcs = set.plain_sources;
    if (variant == Variant::Headers) {
        for (int k = 0; k < s.units; ++k) srcs.push_back(std::format("include/unit_{}.hpp", k));
        srcs.push_back("include/fixture_support.hpp");
    } else {
        srcs.push_back("src/fixture_support.hpp");
    }
    bd += std::format("    srcs = [{}],\n", detail::join(srcs, ", ", "\"", "\""));

    if (!set.module_interfaces.empty()) {
        // The attribute that makes these interface units rather than ordinary
        // TUs. Requires --experimental_cpp_modules AND --features=cpp_modules at
        // build time; the adapter passes both.
        bd += std::format("    module_interfaces = [{}],\n",
                          detail::join(set.module_interfaces, ", ", "\"", "\""));
    }
    bd += std::format("    includes = [\"{}\"],\n",
                      variant == Variant::Headers ? "include" : "src");
    bd += "    copts = [\"-std=c++23\"],\n";
    bd += ")\n";
    detail::write(root / "BUILD.bazel", bd);
}

void emit_all(const std::filesystem::path& root, Variant variant, const Shape& s,
                     std::string_view compiler) {
    emit_mcpp(root, variant, s, compiler);
    emit_cmake(root, variant, s, compiler);
    emit_xmake(root, variant, s, compiler);
    emit_bazel(root, variant, s);
}

}  // namespace bench::fixture
