# Reproduce `mcpplibs.xpkg.lua_stdlib` for the foreign build arms.
#
# That module is not a checked-in file: the xpkg package generates it at build
# time with a `build.mcpp` program. What the program does, though, is small and
# fully specified — it embeds every `.lua` under `src/lua-stdlib/` as a string
# named after the file — so a foreign build system CAN reproduce it, and "mcpp
# runs a build program" is not by itself a boundary. Reproducing it is what
# keeps the cross-engine comparison honest: both arms then compile the same set
# of translation units.
#
# ⚠️ THIS USED TO CARRY A COPIED LIST OF THE ELEVEN MODULES, AND THE COPY DRIFTED.
# A first pass extracted ten of eleven (a regex that missed `base64_lua`), and
# the failure was not "list incomplete" but
#
#     xpkg-executor.cppm:585  error: 'base64_lua' is not a member of ...detail
#
# i.e. it surfaced in a consumer, three files away from the cause. The list is
# now DERIVED — every `.lua` under `src/lua-stdlib`, variable name = basename +
# `_lua` — which is verifiably the same rule build.mcpp applies (checked against
# libxpkg 0.0.57: 11 files, 11 embeddings, names identical). A rule cannot drift
# from itself; a copy of its output can, and did.
#
# `bench/projects/xlings/xmake.lua` implements the same rule in Lua, because
# xmake cannot run a CMake script portably. That is two implementations of one
# RULE, which is a different and much weaker coupling than two copies of one
# LIST — the rule is one line long and its failure is loud (see below).
#
# Usage (from add_custom_command):
#   cmake -DXPKG_ROOT=<pkg> -DOUT=<file> -P embed_lua_stdlib.cmake

if(NOT XPKG_ROOT OR NOT OUT)
  message(FATAL_ERROR "embed_lua_stdlib.cmake needs -DXPKG_ROOT= and -DOUT=")
endif()

# Every .lua under src/lua-stdlib, in a stable order. GLOB is normally the wrong
# tool for a build input — it hides an added file until someone reconfigures —
# but here the SET IS THE CONTRACT: build.mcpp embeds whatever is in that
# directory, so globbing is not an approximation of the list, it is the list.
file(GLOB_RECURSE LUA_FILES "${XPKG_ROOT}/src/lua-stdlib/*.lua")
list(SORT LUA_FILES)
if(NOT LUA_FILES)
  message(FATAL_ERROR
    "no .lua under ${XPKG_ROOT}/src/lua-stdlib — either the package layout "
    "changed or XPKG_ROOT points at the wrong directory. Emitting an empty "
    "module would fail three files away, in a consumer.")
endif()

# Bracket syntax, not a quoted string: a quoted CMake string needs `\;` for a
# literal semicolon, and that backslash reaches the generated C++ verbatim —
# `error: stray '\' in program` on every line of the module preamble.
set(text [[// Generated by bench/projects/xlings/embed_lua_stdlib.cmake — do not edit.
// Mirrors what libxpkg's build.mcpp produces; edit the .lua sources.
module;
export module mcpplibs.xpkg.lua_stdlib;
import std;

export namespace mcpplibs::xpkg::detail {

]])

foreach(src IN LISTS LUA_FILES)
  get_filename_component(stem "${src}" NAME_WE)
  set(var "${stem}_lua")
  file(READ "${src}" body)
  # A C++ raw string literal, so nothing in the Lua needs escaping. The
  # delimiter is one no Lua file contains; if that ever stops being true the
  # generated file will not compile, which is the loud failure we want.
  string(APPEND text "inline const std::string_view ${var} = R\"XLUA(${body})XLUA\"")
  string(APPEND text ";\n\n")
endforeach()

string(APPEND text "} // namespace mcpplibs::xpkg::detail\n")

get_filename_component(outdir "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${outdir}")
file(WRITE "${OUT}" "${text}")
