# Reproduce `mcpplibs.xpkg.lua_stdlib` for the cmake arm of the benchmark.
#
# That module is not a checked-in file: the xpkg package generates it at build
# time with a `build.mcpp` program. What the program does, though, is small and
# fully specified — it embeds ten `.lua` files as strings — so a foreign build
# system CAN reproduce it, and "mcpp runs a build program" is not by itself a
# boundary. Reproducing it is what keeps the cross-engine comparison honest:
# both arms then compile the same set of translation units.
#
# ⚠️ THE MODULE LIST IS COPIED, and copies drift — this one already did. A first
# pass extracted ten of the eleven entries (a regex that missed `base64_lua`),
# and the failure was not "list incomplete" but
#
#     xpkg-executor.cppm:585  error: 'base64_lua' is not a member of ...detail
#
# i.e. it surfaced in a consumer, three files away from the cause. The guard
# below therefore fails on a MISSING FILE rather than trusting the list; the
# alternative — quietly embedding ten of eleven — produces a binary that differs
# from mcpp's while the benchmark reports a clean run.
#
# Regenerate with:
#   grep -oE '\{ *"[A-Za-z0-9_]+" *, *"[^"]+\.lua" *\}' <pkg>/build.mcpp
#
# Usage (from add_custom_command):
#   cmake -DXPKG_ROOT=<pkg> -DOUT=<file> -P embed_lua_stdlib.cmake

if(NOT XPKG_ROOT OR NOT OUT)
  message(FATAL_ERROR "embed_lua_stdlib.cmake needs -DXPKG_ROOT= and -DOUT=")
endif()

# (variable name, path relative to the package root) — mirrors MODULES in
# libxpkg's build.mcpp.
set(LUA_MODULES
  "prelude_lua|src/lua-stdlib/prelude.lua"
  "log_lua|src/lua-stdlib/xim/libxpkg/log.lua"
  "pkginfo_lua|src/lua-stdlib/xim/libxpkg/pkginfo.lua"
  "system_lua|src/lua-stdlib/xim/libxpkg/system.lua"
  "subos_lua|src/lua-stdlib/xim/libxpkg/subos.lua"
  "xvm_lua|src/lua-stdlib/xim/libxpkg/xvm.lua"
  "utils_lua|src/lua-stdlib/xim/libxpkg/utils.lua"
  "pkgmanager_lua|src/lua-stdlib/xim/libxpkg/pkgmanager.lua"
  "elfpatch_lua|src/lua-stdlib/xim/libxpkg/elfpatch.lua"
  "json_lua|src/lua-stdlib/xim/libxpkg/json.lua"
  "base64_lua|src/lua-stdlib/xim/libxpkg/base64.lua")

# Bracket syntax, not a quoted string: a quoted CMake string needs `\;` for a
# literal semicolon, and that backslash reaches the generated C++ verbatim —
# `error: stray '\' in program` on every line of the module preamble.
set(text [[// Generated by bench/projects/xlings/embed_lua_stdlib.cmake — do not edit.
// Mirrors what libxpkg's build.mcpp produces; edit the .lua sources.
module;
export module mcpplibs.xpkg.lua_stdlib;
import std;

export namespace mcpplibs::xpkg::detail {

]])

foreach(entry IN LISTS LUA_MODULES)
  string(REPLACE "|" ";" parts "${entry}")
  list(GET parts 0 var)
  list(GET parts 1 rel)
  set(src "${XPKG_ROOT}/${rel}")
  if(NOT EXISTS "${src}")
    message(FATAL_ERROR
      "lua-stdlib source missing: ${src}\n"
      "the copied module list has drifted from libxpkg's build.mcpp")
  endif()
  file(READ "${src}" body)
  # A C++ raw string literal, so nothing in the Lua needs escaping. The
  # delimiter is one no Lua file contains; if that ever stops being true the
  # generated file will not compile, which is the loud failure we want.
  string(APPEND text "inline const std::string_view ${var} = R\"XLUA(${body})XLUA\"")
  string(APPEND text ";\n\n")
endforeach()

string(APPEND text "} // namespace mcpplibs::xpkg::detail\n")

get_filename_component(outdir "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${outdir}")
file(WRITE "${OUT}" "${text}")
