// The Vulkan compute island.
//
// It is an island for the same reason the CUDA one is: the API underneath is
// C, the memory it operates on is not the program's, and the seam above turns
// both back into C++. What is different is where the device code came from —
// nothing here was compiled by the C++ toolchain. `scale_comp.h` is a
// `const uint32_t[]` that `mcpp.rules.spirv` produced from `shaders/scale.comp`,
// and the driver compiles it for whatever device is present when the program
// runs. That is the property this example exists to show: one artifact, no
// per-GPU build, and a CPU rasteriser is a legitimate device.
#include "saxpy/saxpy.h"

#include <vulkan/vulkan.h>

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

// Generated by mcpp.rules.spirv into the build directory, which the rule puts on
// the include path. The symbol name is derived from the file name:
// `shaders/scale.comp` -> `scale_comp_spv`.
#include "scale_comp.h"

namespace {

struct push_constants { float a; std::uint32_t n; };

// A single allocation holds x, y and out back to back, so the shader needs one
// binding and this file one memory mapping.
constexpr std::uint32_t kVectorsInBuffer = 3;

// Any memory that is host-visible and coherent will do. A discrete GPU offers
// a non-device-local heap with those properties and a software rasteriser has
// nothing else, so this is the one requirement both satisfy; a real workload
// would stage through device-local memory and this one would gain nothing from
// it.
int find_memory_type(VkPhysicalDevice phys, std::uint32_t bits,
                     VkMemoryPropertyFlags want) {
    VkPhysicalDeviceMemoryProperties props{};
    vkGetPhysicalDeviceMemoryProperties(phys, &props);
    for (std::uint32_t i = 0; i < props.memoryTypeCount; ++i)
        if ((bits & (1u << i)) && (props.memoryTypes[i].propertyFlags & want) == want)
            return static_cast<int>(i);
    return -1;
}

// The first device with a compute queue. Not "the fastest": what this program
// demonstrates is that it runs wherever a driver exists, and a machine whose
// only driver is lavapipe is the case the example is written for.
bool pick_device(VkInstance inst, VkPhysicalDevice& out, std::uint32_t& family) {
    std::uint32_t n = 0;
    vkEnumeratePhysicalDevices(inst, &n, nullptr);
    if (n == 0) return false;
    std::vector<VkPhysicalDevice> devices(n);
    vkEnumeratePhysicalDevices(inst, &n, devices.data());
    for (auto d : devices) {
        std::uint32_t qn = 0;
        vkGetPhysicalDeviceQueueFamilyProperties(d, &qn, nullptr);
        std::vector<VkQueueFamilyProperties> qs(qn);
        vkGetPhysicalDeviceQueueFamilyProperties(d, &qn, qs.data());
        for (std::uint32_t i = 0; i < qn; ++i)
            if (qs[i].queueFlags & VK_QUEUE_COMPUTE_BIT) { out = d; family = i; return true; }
    }
    return false;
}

// THE NAME OF THE DEVICE, RECORDED BY THE RUN.
//
// Set only after a successful call, and read through the seam. The CPU
// fallback produces the same four numbers as this island does, so without a
// name printed by the program nothing distinguishes a device run from a silent
// fallback -- which is the one confusion an example about heterogeneous
// compute must not leave in place.
char g_ran_on[256] = "";

} // namespace

extern "C" const char* saxpy_device_name(void) { return g_ran_on; }

extern "C" int saxpy_device(float a, const float* x, const float* y,
                            float* out, unsigned n) {
    if (n == 0) return 0;

    VkApplicationInfo app{};
    app.sType      = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    app.apiVersion = VK_API_VERSION_1_1;
    VkInstanceCreateInfo ici{};
    ici.sType            = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    ici.pApplicationInfo = &app;

    VkInstance inst{};
    if (vkCreateInstance(&ici, nullptr, &inst) != VK_SUCCESS) return 1;

    VkPhysicalDevice phys{};
    std::uint32_t family = 0;
    if (!pick_device(inst, phys, family)) { vkDestroyInstance(inst, nullptr); return 1; }

    const float priority = 1.0f;
    VkDeviceQueueCreateInfo qci{};
    qci.sType            = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
    qci.queueFamilyIndex = family;
    qci.queueCount       = 1;
    qci.pQueuePriorities = &priority;
    VkDeviceCreateInfo dci{};
    dci.sType                = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
    dci.queueCreateInfoCount = 1;
    dci.pQueueCreateInfos    = &qci;

    VkDevice dev{};
    if (vkCreateDevice(phys, &dci, nullptr, &dev) != VK_SUCCESS) {
        vkDestroyInstance(inst, nullptr);
        return 1;
    }

    int rc = 1;
    VkQueue queue{};
    vkGetDeviceQueue(dev, family, 0, &queue);

    const VkDeviceSize bytes = VkDeviceSize(n) * kVectorsInBuffer * sizeof(float);
    VkBufferCreateInfo bci{};
    bci.sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bci.size        = bytes;
    bci.usage       = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

    VkBuffer buffer{};
    VkDeviceMemory memory{};
    VkShaderModule shader{};
    VkDescriptorSetLayout setLayout{};
    VkPipelineLayout pipeLayout{};
    VkPipeline pipeline{};
    VkDescriptorPool pool{};
    VkCommandPool cmdPool{};
    VkFence fence{};

    if (vkCreateBuffer(dev, &bci, nullptr, &buffer) != VK_SUCCESS) goto done;

    {
        VkMemoryRequirements req{};
        vkGetBufferMemoryRequirements(dev, buffer, &req);
        const int type = find_memory_type(phys, req.memoryTypeBits,
                                          VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
                                          | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
        if (type < 0) goto done;
        VkMemoryAllocateInfo mai{};
        mai.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        mai.allocationSize  = req.size;
        mai.memoryTypeIndex = static_cast<std::uint32_t>(type);
        if (vkAllocateMemory(dev, &mai, nullptr, &memory) != VK_SUCCESS) goto done;
        if (vkBindBufferMemory(dev, buffer, memory, 0) != VK_SUCCESS) goto done;

        void* mapped = nullptr;
        if (vkMapMemory(dev, memory, 0, bytes, 0, &mapped) != VK_SUCCESS) goto done;
        auto* v = static_cast<float*>(mapped);
        std::memcpy(v,     x, n * sizeof(float));
        std::memcpy(v + n, y, n * sizeof(float));
        std::memset(v + 2 * n, 0, n * sizeof(float));
        vkUnmapMemory(dev, memory);
    }

    {
        VkShaderModuleCreateInfo smci{};
        smci.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        smci.codeSize = sizeof scale_comp_spv;
        smci.pCode    = scale_comp_spv;
        if (vkCreateShaderModule(dev, &smci, nullptr, &shader) != VK_SUCCESS) goto done;

        VkDescriptorSetLayoutBinding binding{};
        binding.binding         = 0;
        binding.descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        binding.descriptorCount = 1;
        binding.stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
        VkDescriptorSetLayoutCreateInfo dslci{};
        dslci.sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        dslci.bindingCount = 1;
        dslci.pBindings    = &binding;
        if (vkCreateDescriptorSetLayout(dev, &dslci, nullptr, &setLayout) != VK_SUCCESS)
            goto done;

        VkPushConstantRange range{};
        range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
        range.size       = sizeof(push_constants);
        VkPipelineLayoutCreateInfo plci{};
        plci.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        plci.setLayoutCount         = 1;
        plci.pSetLayouts            = &setLayout;
        plci.pushConstantRangeCount = 1;
        plci.pPushConstantRanges    = &range;
        if (vkCreatePipelineLayout(dev, &plci, nullptr, &pipeLayout) != VK_SUCCESS) goto done;

        VkComputePipelineCreateInfo cpci{};
        cpci.sType        = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        cpci.stage.sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        cpci.stage.stage  = VK_SHADER_STAGE_COMPUTE_BIT;
        cpci.stage.module = shader;
        cpci.stage.pName  = "main";
        cpci.layout       = pipeLayout;
        if (vkCreateComputePipelines(dev, VK_NULL_HANDLE, 1, &cpci, nullptr, &pipeline)
            != VK_SUCCESS)
            goto done;
    }

    {
        VkDescriptorPoolSize size{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1};
        VkDescriptorPoolCreateInfo dpci{};
        dpci.sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
        dpci.maxSets       = 1;
        dpci.poolSizeCount = 1;
        dpci.pPoolSizes    = &size;
        if (vkCreateDescriptorPool(dev, &dpci, nullptr, &pool) != VK_SUCCESS) goto done;

        VkDescriptorSetAllocateInfo dsai{};
        dsai.sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        dsai.descriptorPool     = pool;
        dsai.descriptorSetCount = 1;
        dsai.pSetLayouts        = &setLayout;
        VkDescriptorSet set{};
        if (vkAllocateDescriptorSets(dev, &dsai, &set) != VK_SUCCESS) goto done;

        VkDescriptorBufferInfo info{buffer, 0, bytes};
        VkWriteDescriptorSet write{};
        write.sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        write.dstSet          = set;
        write.descriptorCount = 1;
        write.descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        write.pBufferInfo     = &info;
        vkUpdateDescriptorSets(dev, 1, &write, 0, nullptr);

        VkCommandPoolCreateInfo cpi{};
        cpi.sType            = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
        cpi.queueFamilyIndex = family;
        if (vkCreateCommandPool(dev, &cpi, nullptr, &cmdPool) != VK_SUCCESS) goto done;

        VkCommandBufferAllocateInfo cbai{};
        cbai.sType              = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
        cbai.commandPool        = cmdPool;
        cbai.level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        cbai.commandBufferCount = 1;
        VkCommandBuffer cmd{};
        if (vkAllocateCommandBuffers(dev, &cbai, &cmd) != VK_SUCCESS) goto done;

        VkCommandBufferBeginInfo begin{};
        begin.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        begin.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        vkBeginCommandBuffer(cmd, &begin);
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeLayout,
                                0, 1, &set, 0, nullptr);
        const push_constants pc{a, n};
        vkCmdPushConstants(cmd, pipeLayout, VK_SHADER_STAGE_COMPUTE_BIT,
                           0, sizeof pc, &pc);
        // The workgroup size is in the shader (`local_size_x = 64`); the count
        // here has to agree with it, which is why the shader also bounds-checks.
        vkCmdDispatch(cmd, (n + 63) / 64, 1, 1);
        vkEndCommandBuffer(cmd);

        VkFenceCreateInfo fci{};
        fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
        if (vkCreateFence(dev, &fci, nullptr, &fence) != VK_SUCCESS) goto done;

        VkSubmitInfo submit{};
        submit.sType              = VK_STRUCTURE_TYPE_SUBMIT_INFO;
        submit.commandBufferCount = 1;
        submit.pCommandBuffers    = &cmd;
        if (vkQueueSubmit(queue, 1, &submit, fence) != VK_SUCCESS) goto done;
        if (vkWaitForFences(dev, 1, &fence, VK_TRUE, ~0ull) != VK_SUCCESS) goto done;

        void* mapped = nullptr;
        if (vkMapMemory(dev, memory, 0, bytes, 0, &mapped) != VK_SUCCESS) goto done;
        std::memcpy(out, static_cast<const float*>(mapped) + 2 * n, n * sizeof(float));
        vkUnmapMemory(dev, memory);
        rc = 0;
    }

done:
    if (fence)     vkDestroyFence(dev, fence, nullptr);
    if (cmdPool)   vkDestroyCommandPool(dev, cmdPool, nullptr);
    if (pool)      vkDestroyDescriptorPool(dev, pool, nullptr);
    if (pipeline)  vkDestroyPipeline(dev, pipeline, nullptr);
    if (pipeLayout) vkDestroyPipelineLayout(dev, pipeLayout, nullptr);
    if (setLayout) vkDestroyDescriptorSetLayout(dev, setLayout, nullptr);
    if (shader)    vkDestroyShaderModule(dev, shader, nullptr);
    if (memory)    vkFreeMemory(dev, memory, nullptr);
    if (buffer)    vkDestroyBuffer(dev, buffer, nullptr);
    if (rc == 0) {
        VkPhysicalDeviceProperties properties{};
        vkGetPhysicalDeviceProperties(phys, &properties);
        std::snprintf(g_ran_on, sizeof g_ran_on, "%s", properties.deviceName);
    }
    vkDestroyDevice(dev, nullptr);
    vkDestroyInstance(inst, nullptr);
    return rc;
}
