#include <gtest/gtest.h>

import std;
import mcpp.doctor;

using mcpp::doctor::find_fixincludes_banners;

// mcpp#687: GCC's `fixincludes` step writes a frozen copy of the BUILD
// MACHINE's own libc header into `include-fixed`, and mcpp's `-idirafter`
// search order puts it ahead of the glibc a project actually resolves. This
// covers the pure scan `find_fixincludes_banners` — the read side of the
// `mcpp self doctor` check — against a synthetic payload tree, so it needs
// neither a real xim-x-gcc install nor a real doctor run to verify.

namespace {

namespace fs = std::filesystem;

fs::path make_tempdir(std::string_view name) {
    auto base = fs::temp_directory_path()
              / std::format("{}-{}", name,
                            std::chrono::steady_clock::now()
                                .time_since_epoch().count());
    fs::create_directories(base);
    return base;
}

void write_file(const fs::path& p, std::string_view content) {
    fs::create_directories(p.parent_path());
    std::ofstream os(p, std::ios::binary);
    os << content;
}

// The real banner's shape, measured from
// xim-x-gcc/{13.3.0,15.1.0}/lib/gcc/x86_64-linux-gnu/<v>/include-fixed/pthread.h.
constexpr std::string_view kBannerFixture =
    "/*  DO NOT EDIT THIS FILE.\n"
    "\n"
    "    It has been auto-edited by fixincludes from:\n"
    "\n"
    "\t\"/home/xlings/.xlings_data/subos/linux/usr/include/pthread.h\"\n"
    "\n"
    "    This had to be done to correct non-standard usages in the\n"
    "    original, manufacturer supplied header file.  */\n"
    "\n"
    "#ifndef _PTHREAD_H\n"
    "#define _PTHREAD_H 1\n";

// A genuine fixincludes README, unedited — no banner, present in every
// version (including 16.1.0, which ships no frozen header at all).
constexpr std::string_view kReadmeFixture =
    "This directory contains header files fixed by fixincludes.\n"
    "The original files are not modified.\n";

}  // namespace

TEST(DoctorFixincludes, ABannerFileIsReportedWithItsSource) {
    auto root = make_tempdir("mcpp-fixincludes-banner");
    write_file(root / "lib" / "gcc" / "x86_64-linux-gnu" / "13.3.0"
                    / "include-fixed" / "pthread.h", kBannerFixture);

    auto findings = find_fixincludes_banners(root);
    ASSERT_EQ(findings.size(), 1u);
    EXPECT_EQ(findings[0].file, fs::path("lib") / "gcc" / "x86_64-linux-gnu"
                                / "13.3.0" / "include-fixed" / "pthread.h");
    EXPECT_EQ(findings[0].source,
              "/home/xlings/.xlings_data/subos/linux/usr/include/pthread.h");

    fs::remove_all(root);
}

// The exact 16.1.0 shape: an `include-fixed` directory that exists (fixincludes
// always creates it) but holds only its own README, no fixed header at all.
TEST(DoctorFixincludes, AReadmeWithNoBannerIsNotReported) {
    auto root = make_tempdir("mcpp-fixincludes-readme-only");
    write_file(root / "lib" / "gcc" / "x86_64-linux-gnu" / "16.1.0"
                    / "include-fixed" / "README", kReadmeFixture);

    EXPECT_TRUE(find_fixincludes_banners(root).empty());

    fs::remove_all(root);
}

// A fixed header that carries no banner (some fixincludes edits do not add
// one — e.g. a bare wrapped `limits.h`) is not a match either: the check is
// specifically for the auto-edited-FROM-a-source-path shape mcpp#687 is
// about, not for "any file under include-fixed".
TEST(DoctorFixincludes, AFixedHeaderWithoutTheBannerIsNotReported) {
    auto root = make_tempdir("mcpp-fixincludes-no-banner");
    write_file(root / "lib" / "gcc" / "x86_64-linux-gnu" / "13.3.0"
                    / "include-fixed" / "limits.h",
                "/* -*- Mode: C -*- */\n#ifndef _GCC_LIMITS_H_\n");

    EXPECT_TRUE(find_fixincludes_banners(root).empty());

    fs::remove_all(root);
}

// A file that carries the banner text but sits OUTSIDE any `include-fixed`
// directory does not count — the check is scoped to the one directory
// fixincludes actually writes into, not to the whole payload tree.
TEST(DoctorFixincludes, ABannerOutsideIncludeFixedIsNotReported) {
    auto root = make_tempdir("mcpp-fixincludes-outside");
    write_file(root / "lib" / "gcc" / "x86_64-linux-gnu" / "13.3.0"
                    / "include" / "pthread.h", kBannerFixture);

    EXPECT_TRUE(find_fixincludes_banners(root).empty());

    fs::remove_all(root);
}

// Every `include-fixed` directory under the payload root is scanned, not
// only the first one found — a payload that ships more than one fixed
// header (the common case: pthread.h plus others) is reported in full, and
// two DIFFERENT triples under the same payload root (a cross payload's own
// shape) are both covered by one call.
TEST(DoctorFixincludes, MultipleFindingsAreAllReported) {
    auto root = make_tempdir("mcpp-fixincludes-multi");
    write_file(root / "lib" / "gcc" / "x86_64-linux-gnu" / "13.3.0"
                    / "include-fixed" / "pthread.h", kBannerFixture);
    write_file(root / "lib" / "gcc" / "x86_64-linux-gnu" / "13.3.0"
                    / "include-fixed" / "stdio.h", kBannerFixture);

    auto findings = find_fixincludes_banners(root);
    EXPECT_EQ(findings.size(), 2u);

    fs::remove_all(root);
}

// A payload root that does not exist at all (nothing installed under that
// name/version) is not an error — it is the same as "nothing to report".
TEST(DoctorFixincludes, ANonexistentPayloadRootReportsNothing) {
    EXPECT_TRUE(find_fixincludes_banners(
        fs::temp_directory_path() / "mcpp-fixincludes-does-not-exist").empty());
}
