#include <gtest/gtest.h>
import std;
import mcpp.build.graph_shape;

// The header line build.ninja carries is what the fast paths read before any
// plan exists. Three facts ride it -- the graph's shape, the module-edge
// schedule, and (2026.9.5.3+) whether a `--accel` / `--no-accel` override
// chose the device variant -- and the fast paths decline a graph that says
// anything other than "plain build, manifest's own variant".

namespace {

std::filesystem::path write_graph(const std::string& first) {
    static const auto run = std::random_device{}();
    auto dir = std::filesystem::temp_directory_path()
             / ("mcpp-graph-shape-" + std::to_string(run) + "-"
                + std::to_string(std::hash<std::string>{}(first)));
    std::filesystem::create_directories(dir);
    auto p = dir / "build.ninja";
    std::ofstream os(p, std::ios::trunc);
    os << "# Auto-generated by mcpp v0.0.1. Do not edit by hand.\n"
       << first << "\n"
       << "ninja_required_version = 1.11\n";
    return p;
}

} // namespace

TEST(GraphShape, TheHeaderNamesShapeScheduleAndSelection) {
    EXPECT_EQ(mcpp::build::header_line(mcpp::build::GraphShape::Normal, "none", false),
              "# mcpp:graph=normal;schedule=none;accel=default");
    EXPECT_EQ(mcpp::build::header_line(mcpp::build::GraphShape::WithTests, "two-phase", true),
              "# mcpp:graph=test;schedule=two-phase;accel=override");
}

TEST(GraphShape, OnlyAPlainGraphWithTheManifestsVariantIsReplayed) {
    using namespace mcpp::build;
    EXPECT_TRUE(is_plain_build_graph(write_graph(header_line(GraphShape::Normal, "none", false))));
    // An override chose this variant: a plain build must not replay it.
    EXPECT_FALSE(is_plain_build_graph(write_graph(header_line(GraphShape::Normal, "none", true))));
    // The test-shaped graph was already refused.
    EXPECT_FALSE(is_plain_build_graph(write_graph(header_line(GraphShape::WithTests, "none", false))));
}

TEST(GraphShape, AGraphThatPredatesTheFieldIsAMiss) {
    using namespace mcpp::build;
    // Written by a 2026.9.5.2 mcpp: shape and schedule, no selection. It is
    // not known to be the manifest's variant, so it is prepared once more and
    // rewritten with the field -- a miss, never a guess.
    auto p = write_graph("# mcpp:graph=normal;schedule=none");
    EXPECT_EQ(read_shape(p), GraphShape::Normal);
    EXPECT_EQ(read_accel_selection(p), "");
    EXPECT_FALSE(is_plain_build_graph(p));
}
