#!/bin/sh
# toyc -- the whole compiler for `.toy`.
#
#   toyc.sh <input.toy> <output.cpp> <entry-name>
#
# A `.toy` file is a list of integers, one per line, with `#` comments. The
# entry point returns their sum. This is not a language; it is the smallest
# thing that is compiled by something mcpp does not drive.
#
# awk rather than `paste | bc`: bc is not installed on every runner this
# repository's CI uses, and a missing summator produced a program that built,
# ran, and printed the wrong number.
set -eu
in=$1; out=$2; name=$3
sum=$(awk '{ sub(/#.*/, ""); gsub(/[ \t]/, "") } /^-?[0-9]+$/ { s += $0 } END { print s + 0 }' "$in")
mkdir -p "$(dirname "$out")"
cat > "$out" <<EOT
// Generated by toyc from $(basename "$in"). Do not edit.
extern "C" int toy_${name}() { return ${sum}; }
EOT
